apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searx
data:
  settings.yml: |
    use_default_settings: true

    general:
      debug: false
      instance_name: "SearXNG"

    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json

    server:
      port: 8080
      bind_address: "0.0.0.0"
      secret_key: "c35-searxng-secret-key-cluster"
      limiter: false
      image_proxy: false

    outgoing:
      request_timeout: 12.0
      max_request_timeout: 15.0
      proxies:
        all://:
          - http://c35-proxy-cf-warp.c35.svc.cluster.local:8080
