#!/usr/bin/env python3
"""
seed_object_taxonomy.py

Fetches and compiles Google Product Taxonomy (EN & ID) into ai.object_normalizer
and ai.object_alias tables with standard numeric IDs, materialized paths,
and category rollups.

Run:
    python seed_object_taxonomy.py [--emit-sql output.sql] [--db-url postgresql://...]
"""

import argparse
import re
import sys
import urllib.request
from typing import Dict, List, Optional, Tuple

GPT_EN_URL = "https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt"
GPT_ID_URL = "https://www.google.com/basepages/producttype/taxonomy-with-ids.id-ID.txt"


def slug_norm(text: str) -> str:
    """Normalize string to snake_case slug matching ai.slug_norm() in PostgreSQL."""
    if not text:
        return ""
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text)
    return text.strip("_")


def parse_taxonomy_file(content: str) -> Dict[int, List[str]]:
    """
    Parses Google Product Taxonomy format:
    e.g. "2271 - Food, Beverages & Tobacco > Beverages > Dairy Drinks > Milk"
    Returns: {id: [part1, part2, ...]}
    """
    out = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(" - ", 1)
        if len(parts) != 2:
            continue
        try:
            cat_id = int(parts[0].strip())
        except ValueError:
            continue
        crumbs = [c.strip() for c in parts[1].split(">")]
        out[cat_id] = crumbs
    return out


def build_taxonomy_tree(
    en_cats: Dict[int, List[str]], id_cats: Dict[int, List[str]]
) -> Tuple[List[dict], List[dict]]:
    """
    Builds normalizer nodes and aliases.
    """
    nodes = []
    aliases = []

    # Map paths to node IDs for parent linking
    path_to_id: Dict[str, int] = {}
    # Track slug counts for uniqueness
    seen_slugs: Dict[str, int] = {}

    for cat_id, crumbs in sorted(en_cats.items(), key=lambda x: len(x[1])):
        slug_parts = [slug_norm(c) for c in crumbs]
        raw_slug = slug_parts[-1]

        # Ensure slug is unique and within VARCHAR(64)
        candidate = raw_slug
        if candidate in seen_slugs or candidate in {
            'consumable', 'service', 'goods', 'drink', 'food', 'utility', 'transport',
            'milk', 'coffee', 'internet', 'electricity', 'staple', 'staple_rice',
            'staple_noodle', 'fried_rice', 'white_rice', 'instant_noodle',
        }:
            candidate = f"{slug_parts[-2]}_{raw_slug}" if len(slug_parts) > 1 else f"{raw_slug}_{cat_id}"
        if candidate in seen_slugs:
            candidate = f"{raw_slug}_{cat_id}"
        if len(candidate) > 60:
            candidate = candidate[:60].rstrip("_")
        if candidate in seen_slugs:
            candidate = f"{candidate[:50]}_{cat_id}"
        slug = candidate
        seen_slugs[slug] = cat_id

        path = ".".join(slug_parts)
        depth = len(crumbs) - 1

        # Determine parent
        parent_id = None
        if len(crumbs) > 1:
            parent_path = ".".join(slug_parts[:-1])
            parent_id = path_to_id.get(parent_path)

        path_to_id[path] = cat_id

        # Rollups: L1 (depth 1) and L2 (depth 2)
        l1_category_id = None
        l2_category_id = None
        if len(crumbs) > 1:
            l1_path = ".".join(slug_parts[:2])
            l1_category_id = path_to_id.get(l1_path) or cat_id
        if len(crumbs) > 2:
            l2_path = ".".join(slug_parts[:3])
            l2_category_id = path_to_id.get(l2_path) or cat_id

        nodes.append(
            {
                "id": cat_id,
                "slug": slug,
                "parent_id": parent_id,
                "path": path,
                "depth": depth,
                "l1_category_id": l1_category_id,
                "l2_category_id": l2_category_id,
                "kind": "category",
            }
        )

        # Aliases (EN)
        en_name = crumbs[-1]
        aliases.append(
            {
                "obj_id": cat_id,
                "lang": "en",
                "name": en_name,
                "name_norm": slug_norm(en_name),
                "is_canonical": True,
            }
        )

        # Aliases (ID) if present
        if cat_id in id_cats:
            id_name = id_cats[cat_id][-1]
            aliases.append(
                {
                    "obj_id": cat_id,
                    "lang": "id",
                    "name": id_name,
                    "name_norm": slug_norm(id_name),
                    "is_canonical": True,
                }
            )

    return nodes, aliases


def generate_sql(nodes: List[dict], aliases: List[dict]) -> str:
    lines = [
        "-- Auto-generated by seed_object_taxonomy.py",
        "-- Seeds official Google Product Taxonomy nodes and multilingual aliases",
        "",
    ]

    # Batch insert nodes in chunks of 500 to keep statements reasonable
    chunk_size = 500
    for i in range(0, len(nodes), chunk_size):
        chunk = nodes[i : i + chunk_size]
        lines.append("INSERT INTO ai.object_normalizer (id, slug, parent_id, path, depth, l1_category_id, l2_category_id, kind) VALUES")
        node_tuples = []
        for n in chunk:
            parent_sql = str(n["parent_id"]) if n["parent_id"] is not None else "NULL"
            l1_sql = str(n["l1_category_id"]) if n["l1_category_id"] is not None else "NULL"
            l2_sql = str(n["l2_category_id"]) if n["l2_category_id"] is not None else "NULL"
            slug_esc = n["slug"].replace("'", "''")
            path_esc = n["path"].replace("'", "''")
            node_tuples.append(
                f"    ({n['id']}, '{slug_esc}', {parent_sql}, '{path_esc}', {n['depth']}, {l1_sql}, {l2_sql}, '{n['kind']}')"
            )
        lines.append(",\n".join(node_tuples))
        lines.append("ON CONFLICT DO NOTHING;\n")

    # Batch insert aliases in chunks of 500
    for i in range(0, len(aliases), chunk_size):
        chunk = aliases[i : i + chunk_size]
        lines.append("INSERT INTO ai.object_alias (id, obj_id, lang, name, name_norm, is_canonical, verified) VALUES")
        alias_tuples = []
        for idx_offset, a in enumerate(chunk):
            real_idx = 1000000 + i + idx_offset
            name_esc = a["name"].replace("'", "''")
            norm_esc = a["name_norm"].replace("'", "''")
            canon_sql = "TRUE" if a["is_canonical"] else "FALSE"
            alias_tuples.append(
                f"    ({real_idx}, {a['obj_id']}, '{a['lang']}', '{name_esc}', '{norm_esc}', {canon_sql}, TRUE)"
            )
        lines.append(",\n".join(alias_tuples))
        lines.append("ON CONFLICT DO NOTHING;\n")

    return "\n".join(lines)


def fetch_url(url: str) -> Optional[str]:
    print(f"Fetching {url}...")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except Exception as e:
        print(f"Notice: could not fetch {url}: {e}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(description="Seed Object Taxonomy")
    parser.add_argument("--emit-sql", help="Path to write compiled SQL", default=None)
    args = parser.parse_args()

    en_content = fetch_url(GPT_EN_URL)
    if not en_content:
        print("Error: could not fetch primary English taxonomy.", file=sys.stderr)
        return

    id_content = fetch_url(GPT_ID_URL) or ""

    en_cats = parse_taxonomy_file(en_content)
    id_cats = parse_taxonomy_file(id_content) if id_content else {}

    print(f"Loaded {len(en_cats)} EN categories, {len(id_cats)} ID categories.")
    nodes, aliases = build_taxonomy_tree(en_cats, id_cats)
    print(f"Compiled {len(nodes)} normalizer nodes, {len(aliases)} multilingual aliases.")

    if args.emit_sql:
        sql = generate_sql(nodes, aliases)
        with open(args.emit_sql, "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"Wrote compiled SQL to {args.emit_sql}")


if __name__ == "__main__":
    main()
