apiVersion: v1
kind: Service
metadata:
  name: c35-proxy-cf-warp
  namespace: c35
  labels:
    app.kubernetes.io/name: c35-proxy-cf-warp
    app.kubernetes.io/part-of: c35
    app.kubernetes.io/component: egress
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: c35-proxy-cf-warp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
