import 'dart:io';

import 'package:path/path.dart' as p;

const _versionPrefix = '''// DO NOT EDIT THIS FILE, GENERATED BY update_version.dart
//''';

final _versionRegex = RegExp(r'^version:\s*(\d+)\.(\d+)\.(\d+)\+(\d+)$', multiLine: true);

String deployAppDir(String repoRoot) => p.join(repoRoot, 'clients', 'app');

String _pubspecPath(String repoRoot) => p.join(deployAppDir(repoRoot), 'pubspec.yaml');

(int major, int build) versionReadPubspec(String repoRoot) {
  final match = _pubspecMatch(repoRoot);
  return (int.parse(match.group(1)!), int.parse(match.group(4)!));
}

RegExpMatch _pubspecMatch(String repoRoot) {
  final content = File(_pubspecPath(repoRoot)).readAsStringSync();
  final match = _versionRegex.firstMatch(content);
  if (match == null) {
    throw StateError('Could not parse version from pubspec.yaml (expected version: MAJOR.MINOR.PATCH+BUILD)');
  }
  return match;
}

String versionReadPubspecFull(String repoRoot) {
  final m = _pubspecMatch(repoRoot);
  return '${m.group(1)}.${m.group(2)}.${m.group(3)}+${m.group(4)}';
}

void versionWritePubspec(String repoRoot, int major, int build) {
  final newLine = 'version: $major.$build.0+$build';
  final file = File(_pubspecPath(repoRoot));
  final content = file.readAsStringSync();
  file.writeAsStringSync(content.replaceFirst(_versionRegex, newLine));
}

void versionStampWrite(String repoRoot, String version) {
  final full = versionReadPubspecFull(repoRoot);
  final dartPath = p.join(deployAppDir(repoRoot), 'lib', 'c', 'parts', 'csai__version.dart');
  final file = File(dartPath);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(
    '''$_versionPrefix

// ================================================================ Version
const csaiVersion = '$version';
const csaiVersionFull = '$full';
''',
  );
}

String versionStampSync(String repoRoot) {
  final (_, build) = versionReadPubspec(repoRoot);
  final version = '$build';
  versionStampWrite(repoRoot, version);
  return version;
}

String versionStampBump(String repoRoot) {
  final (major, build) = versionReadPubspec(repoRoot);
  final newBuild = build + 1;
  versionWritePubspec(repoRoot, major, newBuild);
  final version = '$newBuild';
  versionStampWrite(repoRoot, version);
  return version;
}
