[package]
name = "c35_mod_hint"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
c35_ctx = { path = "../system/ctx", package = "c35_ctx" }
c35_proto = { path = "../proto", package = "c35_proto" }
c35_store = { path = "../store", package = "c35_store" }
