[package]
name = "c35_fcm"
version.workspace = true
edition.workspace = true
description = "c35 FCM HTTP v1 data sender"

[dependencies]
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
