[package]
name = "c35_wire_ws"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
c35_ctx = { path = "../system/ctx", package = "c35_ctx" }
c35_mod_chat = { path = "../mod_chat", package = "c35_mod_chat" }
c35_mod_consumption = { path = "../mod_consumption", package = "c35_mod_consumption" }
c35_mod_billing = { path = "../mod_billing", package = "c35_mod_billing" }
c35_mod_channel = { path = "../mod_channel", package = "c35_mod_channel" }
c35_mod_identity = { path = "../mod_identity", package = "c35_mod_identity" }
async-nats = { workspace = true }
c35_mod_llm = { path = "../mod_llm", package = "c35_mod_llm" }
tokio-util = "0.7"
c35_wire_http = { path = "../wire_http", package = "c35_wire_http" }
c35_proto = { path = "../proto", package = "c35_proto" }
c35_wire = { path = "../wire", package = "c35_wire" }
futures-util = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
