[package]
name = "c35_mod_device"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = "0.22"
blake3 = "1"
chrono = { workspace = true }
dashmap = { workspace = true }
hmac = "0.12"
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10"
sqlx = { workspace = true }
tokio = { workspace = true }
async-nats = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
c35_mod_log = { path = "../mod_log", package = "c35_mod_log" }
c35_mod_admin = { path = "../mod_admin", package = "c35_mod_admin" }
c35_mod_event = { path = "../mod_event", package = "c35_mod_event" }
c35_proto = { path = "../proto", package = "c35_proto" }
c35_nats = { path = "../system/nats", package = "c35_nats" }
c35_store = { path = "../store", package = "c35_store" }
c35_mod_drive = { path = "../mod_drive", package = "c35_mod_drive" }

[dev-dependencies]
tokio = { workspace = true }
