apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: build
  labels:
    app: buildkit
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        kubernetes.io/hostname: 10.0.85.142
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.19.0
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --config
            - /etc/buildkit/buildkitd.toml
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "2"
              memory: 6Gi
            limits:
              cpu: "4"
              memory: 14Gi
          volumeMounts:
            - name: buildkit-cache
              mountPath: /var/lib/buildkit
            - name: buildkit-config
              mountPath: /etc/buildkit
              readOnly: true
      volumes:
        - name: buildkit-cache
          hostPath:
            path: /var/lib/alienai/buildkit
            type: DirectoryOrCreate
        - name: buildkit-config
          configMap:
            name: buildkit-config
