apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-data
  namespace: build
  labels:
    app: buildkit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 50Gi