[workspace]
resolver = "2"
members = [
    "c_remote_core",
    "c_remote_windows",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["AlienAI"]

[workspace.dependencies]
anyhow = "1"
blake3 = "1"
futures-util = "0.3"
zip = "2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "net", "time", "sync"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-native-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry"] }
urlencoding = "2"
webrtc = "0.11"
base64 = "0.22"

[profile.dev]
debug = 1
split-debuginfo = "unpacked"
