[package]
name = "c35_wire_http"
version.workspace = true
edition.workspace = true

[dependencies]
axum = { workspace = true }
prost = { workspace = true }
sqlx = { workspace = true }
c35_ctx = { path = "../system/ctx", package = "c35_ctx" }
c35_mod_identity = { path = "../mod_identity", package = "c35_mod_identity" }
c35_mod_referral = { path = "../mod_referral", package = "c35_mod_referral" }
c35_proto = { path = "../proto", package = "c35_proto" }
