// DO NOT EDIT THIS FILE, GENERATED BY update_version.dart
//

// ================================================================ Version
const csaiVersion = '234';
const csaiVersionFull = '20.234.0+234';
