// DO NOT EDIT THIS FILE, GENERATED BY update_version.dart
//

// ================================================================ Version
const csaiVersion = '275';
const csaiVersionFull = '20.275.0+275';
