// DO NOT EDIT THIS FILE, GENERATED BY update_version.dart
//

// ================================================================ Version
const csaiVersion = '236';
const csaiVersionFull = '20.236.0+236';
