apiVersion: v1
kind: PersistentVolume
metadata:
  name: yb-data-restored2
  annotations:
    pv.kubernetes.io/provisioned-by: blockvolume.csi.oraclecloud.com
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oci-bv
  csi:
    driver: blockvolume.csi.oraclecloud.com
    fsType: ext4
    volumeHandle: ocid1.volume.oc1.ap-batam-1.abrguljrfqmcjsbdf74r3abwkvrdwfxm5kbcwnrnl2qfef47goxvwvdnq7jq
    volumeAttributes:
      vpusPerGB: "10"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - AP-BATAM-1-AD-1
