[package]
name = "c35_mod_voice"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
base64 = "0.22"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
c35_mod_billing = { path = "../mod_billing", package = "c35_mod_billing" }
c35_mod_log = { path = "../mod_log", package = "c35_mod_log" }
c35_proto = { path = "../proto", package = "c35_proto" }
c35_store = { path = "../store", package = "c35_store" }

[dev-dependencies]
tokio = { workspace = true }
