[package]
name = "c35_mod_referral"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
c35_store = { path = "../store", package = "c35_store" }
c35_mod_admin = { path = "../mod_admin", package = "c35_mod_admin" }
c35_proto = { path = "../proto", package = "c35_proto" }
